# Generated by Django 5.2.1 on 2025-07-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_usuario_es_vendedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
