# Generated by Django 5.2.1 on 2025-07-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
