# Generated by Django 5.2.1 on 2025-07-19 18:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Variante_p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo')], max_length=10)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en Stock')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='cliente.producto')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'unique_together': {('producto', 'color')},
            },
        ),
    ]
