# Generated by Django 5.2.1 on 2025-07-19 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_producto_variante_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_base',
        ),
        migrations.AlterField(
            model_name='variante_p',
            name='color',
            field=models.CharField(choices=[('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo')], max_length=10, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='variante_p',
            name='imagen',
            field=models.ImageField(upload_to='productos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='variante_p',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='Sku/código'),
        ),
        migrations.AlterField(
            model_name='variante_p',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en stock'),
        ),
    ]
