# Generated by Django 5.2.1 on 2025-08-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante_p',
            name='categoria',
            field=models.CharField(choices=[('Niños', 'Niños'), ('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default=1, max_length=10, verbose_name='Categoría'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variante_p',
            name='talla',
            field=models.IntegerField(default=1, verbose_name='Talla'),
            preserve_default=False,
        ),
    ]
